//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playgrounds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspecation
    {
        public int InspecationID { get; set; }
        public Nullable<int> Playground_ID { get; set; }
        public string InspecationMan { get; set; }
        public string PlaygroundCondition { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> InspecationCreatedDate { get; set; }
    
        public virtual playground playground { get; set; }
    }
}
