//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playgrounds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class playground
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public playground()
        {
            this.Inspecations = new HashSet<Inspecation>();
        }
    
        public int PlaygroundID { get; set; }
        public string PlayGroundName { get; set; }
        public string PlaygroundOther { get; set; }
        public Nullable<System.DateTime> PlaygroundCreatedDate { get; set; }
        public string User_ID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspecation> Inspecations { get; set; }
    }
}
